version: '3'
services:
  mongodb:
    image: "javi3143/mongocatalogue"
    ports:
      - "83:27017"
    restart: always
  nginx:
    image: "javi3143/nginxvideo"
    ports:
      - "81:1935"
      - "84:80"
    restart: always
  myflix:
    build: .
    ports:
      - "80:5000"
    env_file: .env
    links:
      - mysql:dbserver
    restart: always
  mysql:
    image: "mysql/mysql-server:5.7"
    env_file: .env-mysql
    restart: always
